--- !metadata
doc-type: veredi.config
version: 2020-05-06

--- !repository
owner:
  type: veredi.repository.${this}.file-tree
  codec: veredi.codec.yaml
  directory: test/owner/repository/owner/
  # connect data here for DBs?
campaign:
  type: veredi.repository.${this}.file-tree
  codec: veredi.codec.yaml
  directory: test/owner/repository/campaign/
session:
  type: veredi.repository.${this}.file-tree
  codec: veredi.codec.yaml
  directory: test/owner/repository/session/
player:
  type: veredi.repository.${this}.file-tree
  codec: veredi.codec.yaml
  directory: test/owner/repository/player/

  # and more...

# and more?
