--- !metadata
record-type: veredi.config
version: 2020-05-26

source: veredi.config
author: Cole Brown
date:   2020-05-26

system: configuration
name: veredi.config
display-name: Veredi Configuration


--- !configuration

data:
  game:
    repository:
      type: veredi.repository.file-tree
      directory: ../repository/file-tree
      sanitize: veredi.sanitize.human.path-safe
    codec: veredi.codec.yaml

  template:
    repository:
      type: veredi.repository.file-tree
      directory: ../repository/file-tree
      sanitize: veredi.sanitize.human.path-safe
    codec: veredi.codec.yaml

input:
  type: veredi.input.system
  command: veredi.input.commander
  history: veredi.input.historian
  parser:
    math: veredi.math.d20.parser


# and more?
