--- !metadata
record-type: veredi.config
version: 2020-05-26

source: veredi.config
author: Cole Brown
date:   2020-05-26

system: configuration
name: veredi.config
display-name: Veredi Configuration


--- !configuration

data:
  repository:
    type: veredi.repository.file-tree
    directory: test-target-repo/file-tree
    sanitize: veredi.paths.sanitize.human
  serdes: veredi.serdes.yaml
  codec: veredi.codec.codec


registration:
  - register:
      name: Veredi
      dotted: veredi
    path:
      root: ../../../..  # Relative from here.
      registrees:
        run: [ __register__ ]
        test: [ __register_ut_ ]
      registrars:
        run: [ __registrar__ ]
        test: [ __registrar_ut_ ]
      # ignore:
      #   files:
      #     - strings
      #     - !regex "\bregex ?(here)?"
      #     - data
      #     - !regex "^[a-z]+_test"
      #   directories:
      #     - strings
      #     - !regex "\bregex ?(here)?"
      #     - data
      #     - !regex "^[a-z]+_test"
    # unit-test: true/false to force
  # - register: my-module
  #   path:
  #     run: [ register ]


# and more?
