--- !metadata
record-type: veredi.config
version: 2020-05-26

source: veredi.config
author: Cole Brown
date:   2020-05-26

system: configuration
name: veredi.config
display-name: Veredi Configuration


--- !configuration

data:
  repository:
    type: veredi.repository.file-tree
    directory: test-target-repo/file-tree
    sanitize: veredi.paths.sanitize.human
  serdes: veredi.serdes.yaml


# and more?
