--- !metadata
record-type: veredi.config
version: 2020-05-26

source: veredi.config
author: Cole Brown
date:   2020-05-26

system: configuration
name: veredi.config
display-name: Veredi Configuration


--- !configuration

data:
  repository:
    type: veredi.repository.file-tree
    directory: ../repository/file-tree
    sanitize: veredi.sanitize.human.path-safe
  codec: veredi.codec.yaml


input:
  type: veredi.interface.input.system
  command: veredi.interface.input.commander
  history: veredi.interface.input.historian
  parser:
    math: veredi.math.d20.parser


rules:
  type: veredi.rules.d20
  skill: veredi.rules.d20.skill.system
  combat: veredi.rules.d20.combat.system

  ability: veredi.rules.d20.ability
  health: veredi.rules.d20.health
  movement: veredi.rules.d20.movement

# and more?
