--- !metadata

record-type: veredi.config
version: 2020-07-23

source: veredi.config
author: Cole Brown
date:   2020-07-23

system: configuration
name: veredi.config
display-name: Veredi Configuration


--- !configuration

data:
  repository:
    type: veredi.repository.file-tree
    directory: ../repository/file-tree
    sanitize: veredi.paths.sanitize.human
  serdes: veredi.serdes.yaml
  codec: veredi.codec.codec


registration:
  - register:
      name: Veredi
      dotted: veredi
    path:
      root: ../../../..  # Relative from here.
      registrees:
        run: [ __register__ ]
        test: [ __register_ut_ ]
      registrars:
        run: [ __registrar__ ]
        test: [ __registrar_ut_ ]
      # ignore:
      #   files:
      #     - strings
      #     - !regex "\bregex ?(here)?"
      #     - data
      #     - !regex "^[a-z]+_test"
      #   directories:
      #     - strings
      #     - !regex "\bregex ?(here)?"
      #     - data
      #     - !regex "^[a-z]+_test"
    # unit-test: true/false to force
  # - register: my-module
  #   path:
  #     root: /srv/veredi/extra/
  #     run: [ register ]


rules:
  type: veredi.rules.d20.pf2.info
  skill: veredi.rules.d20.pf2.skill.system
  combat: veredi.rules.d20.pf2.combat.system

  ability: veredi.rules.d20.pf2.ability
  health: veredi.rules.d20.pf2.health
  movement: veredi.rules.d20.pf2.movement


server:
  mediator:
    type: veredi.interface.mediator.websocket.server
    serdes: veredi.serdes.json
    codec: veredi.codec.codec
    hostname: 127.0.0.1  # Can't use 'localhost' or IPv6 for now...
    port: 13369
    ssl: false

  input:
    type: veredi.interface.input.system
    command: veredi.interface.input.commander
    history: veredi.interface.input.historian
    parser:
      math: veredi.math.d20.parser

  output:
    type: veredi.interface.output.system


client:
  mediator:
    type: veredi.interface.mediator.websocket.client
    serdes: veredi.serdes.json
    codec: veredi.codec.codec
    hostname: 127.0.0.1  # Can't use 'localhost' or IPv6 for now...
    port: 13369
    ssl: false

# and more?
